# A generic, single database configuration.

[alembic]
script_location = alembic
sqlalchemy.url = postgresql+asyncpg://nanibot:nanibot_secret@localhost:5432/nanibot_db

[post_write_hooks]

[logging]
default_handler = stream

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = stream

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = stream
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_stream]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
