import uuid
import logging
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import Optional
from app.core.database import get_db
from app.core.deps import get_current_user_optional
from app.models.user import User
from app.models.wisdom import ChatSession, ChatMessage
from app.schemas.chat import ChatRequest, ChatResponse, ChatSource, StructuredResponse
from app.services.safety import classify_risk, get_safety_preamble, EMERGENCY_RESPONSE
from app.services.rag import semantic_search
from app.services.llm import chat_with_gemini

router = APIRouter(prefix="/api/chat", tags=["chat"])
logger = logging.getLogger(__name__)


@router.post("/message", response_model=ChatResponse)
async def send_message(
    request: ChatRequest,
    db: AsyncSession = Depends(get_db),
    current_user: Optional[User] = Depends(get_current_user_optional),
):
    # ── 1. Safety Classification ─────────────────────────────────────────────
    risk_level, is_health_related, is_emergency = classify_risk(request.message)

    if is_emergency:
        # Get or create session
        session_id = request.session_id or str(uuid.uuid4())
        session = await _get_or_create_session(db, session_id, current_user)

        msg = ChatMessage(
            session_id=session.id,
            role="assistant",
            content=EMERGENCY_RESPONSE,
            risk_level="CRITICAL",
            language=request.language,
        )
        db.add(msg)
        await db.commit()
        await db.refresh(msg)

        return ChatResponse(
            message_id=msg.id,
            session_id=session_id,
            response_text=EMERGENCY_RESPONSE,
            structured=None,
            sources=[],
            source_explanation="Safety override — emergency symptoms detected",
            risk_level="CRITICAL",
            is_health_related=True,
            language=request.language,
        )

    # ── 2. RAG Retrieval ─────────────────────────────────────────────────────
    retrieved = semantic_search(query=request.message, n_results=5)

    # ── 3. LLM Generation ────────────────────────────────────────────────────
    llm_result = chat_with_gemini(
        query=request.message,
        retrieved_context=retrieved,
        is_health_related=is_health_related,
        language=request.language,
    )

    # ── 4. Prepend safety preamble for health queries ─────────────────────────
    safety_preamble = get_safety_preamble(risk_level, is_health_related)
    final_text = safety_preamble + llm_result["response_text"]

    # ── 5. Build sources list ─────────────────────────────────────────────────
    sources = []
    source_ids = []
    for item in retrieved[:3]:
        meta = item.get("metadata", {})
        if item.get("similarity_score", 0) < 0.3:
            continue
        entry_id = meta.get("id")
        if entry_id:
            sources.append(ChatSource(
                id=int(entry_id),
                title=meta.get("title", "Traditional Wisdom"),
                category=meta.get("category", "General"),
                evidence_label=meta.get("evidence_label", "insufficient_info"),
                region=meta.get("region"),
                source_type="traditional_archive",
            ))
            source_ids.append(str(entry_id))

    # ── 6. Source explanation ─────────────────────────────────────────────────
    if sources:
        source_explanation = (
            f"This response draws from {len(sources)} traditional wisdom {'entry' if len(sources) == 1 else 'entries'} "
            f"in our knowledge archive, synthesized by AI. Traditional practices are presented as cultural knowledge, "
            f"not medical advice."
        )
    else:
        source_explanation = (
            "This response is generated by AI based on general traditional knowledge. "
            "No specific archived entry was retrieved for this query."
        )

    # ── 7. Build structured response object ───────────────────────────────────
    structured_out = None
    if llm_result.get("structured"):
        s = llm_result["structured"]
        structured_out = StructuredResponse(
            traditional_wisdom=s.get("traditional_wisdom", ""),
            why_people_use_it=s.get("why_people_use_it", ""),
            what_science_says=s.get("what_science_says", ""),
            safety_note=s.get("safety_note", ""),
            when_to_see_doctor=s.get("when_to_see_doctor"),
            evidence_label=s.get("evidence_label", "insufficient_info"),
            risk_level=s.get("risk_level", risk_level),
        )
        # Override risk_level with AI classification if higher
        ai_risk = s.get("risk_level", "LOW")
        if _risk_rank(ai_risk) > _risk_rank(risk_level):
            risk_level = ai_risk

    # ── 8. Persist to database ────────────────────────────────────────────────
    import json
    session_id = request.session_id or str(uuid.uuid4())
    session = await _get_or_create_session(db, session_id, current_user)

    # Save user message
    user_msg = ChatMessage(
        session_id=session.id,
        role="user",
        content=request.message,
        risk_level=risk_level,
        language=request.language,
    )
    db.add(user_msg)

    # Save assistant message
    assistant_msg = ChatMessage(
        session_id=session.id,
        role="assistant",
        content=final_text,
        sources_used=json.dumps(source_ids),
        risk_level=risk_level,
        language=request.language,
    )
    db.add(assistant_msg)
    await db.commit()
    await db.refresh(assistant_msg)

    return ChatResponse(
        message_id=assistant_msg.id,
        session_id=session_id,
        response_text=final_text,
        structured=structured_out,
        sources=sources,
        source_explanation=source_explanation,
        risk_level=risk_level,
        is_health_related=is_health_related,
        language=request.language,
    )


@router.get("/sessions/{session_id}/history")
async def get_chat_history(
    session_id: str,
    db: AsyncSession = Depends(get_db),
    current_user: Optional[User] = Depends(get_current_user_optional),
):
    result = await db.execute(
        select(ChatSession).where(ChatSession.session_id == session_id)
    )
    session = result.scalar_one_or_none()
    if not session:
        return {"messages": [], "session_id": session_id}

    msgs_result = await db.execute(
        select(ChatMessage)
        .where(ChatMessage.session_id == session.id)
        .order_by(ChatMessage.created_at)
    )
    messages = msgs_result.scalars().all()

    return {
        "session_id": session_id,
        "messages": [
            {
                "id": m.id,
                "role": m.role,
                "content": m.content,
                "risk_level": m.risk_level,
                "language": m.language,
                "created_at": m.created_at.isoformat() if m.created_at else None,
            }
            for m in messages
        ],
    }


async def _get_or_create_session(db: AsyncSession, session_id: str, user: Optional[User]) -> ChatSession:
    result = await db.execute(select(ChatSession).where(ChatSession.session_id == session_id))
    session = result.scalar_one_or_none()
    if not session:
        session = ChatSession(
            session_id=session_id,
            user_id=user.id if user else None,
        )
        db.add(session)
        await db.commit()
        await db.refresh(session)
    return session


def _risk_rank(risk: str) -> int:
    return {"LOW": 0, "MEDIUM": 1, "HIGH": 2, "CRITICAL": 3}.get(risk, 0)
